// <auto-generated />
using System;
using BizModSwapBot.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BizModSwapBot.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722054522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BizModSwapBot.Domain.Swaps.DesiredSlot", b =>
                {
                    b.Property<Guid>("SwapRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SwapRequestId", "ModuleCode", "ClassNo");

                    b.ToTable("DesiredSlots", (string)null);
                });

            modelBuilder.Entity("BizModSwapBot.Domain.Swaps.SwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcadYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaveClassNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaveDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaveModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SwapRequests", (string)null);
                });

            modelBuilder.Entity("BizModSwapBot.Domain.Swaps.DesiredSlot", b =>
                {
                    b.HasOne("BizModSwapBot.Domain.Swaps.SwapRequest", null)
                        .WithMany("WantSlots")
                        .HasForeignKey("SwapRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BizModSwapBot.Domain.Swaps.SwapRequest", b =>
                {
                    b.Navigation("WantSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
