@BizModSwapBot.API_HostAddress = http://localhost:5107


GET http://nusbizmodswapbot.runasp.net/api/swap

### Test POST
POST https://nusbizmodswapbot.runasp.net/api/swap
Content-Type: application/json

{
  "telegramUserId": 12345,
  "telegramUsername": "tele_user",
  "acadYear": "2025-2026",
  "semester": 1,
  "haveModuleCode": "MKT1705A",
  "haveClassNo": "A1",
  "haveDetails": "test",
  "wantSlots": [
    {
      "moduleCode": "MKT1705A",
      "classNo": "A2"
    }
  ]
}
###
